name: documentation
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate documentation
        run: javadoc -d doc/documentacion Java/githubAction/src/main/java/org/example/githubaction/*.java
      - name: Commit automático del README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update DOC con la nueva documentación"
          file_pattern: 'docs/**'
