name: documentation
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate documentation
        run: javadoc -d doc/documentacion githubAction/src/main/java/org/example/githubaction/*.java
    
